site_name: 'Jikan API Documentation'
site_description: 'PHP API Documentation for Jikan, the unofficial MyAnimeList.net API'
site_author: '@irfanDahir'
site_url: 'https://jikan.moe'    

# Configuration
theme:
  name: 'material'
  language: 'en'

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


  font:
    text: 'Inter'
    code: 'Roboto Mono'

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true


  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/favicon.png
  icon:
    # logo: assets/logo.png

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - toc.integrate 
    - navigation.top
    - search.share
    - search.highlight
    - search.suggest
    - header.autohide


plugins:
  - search:
      lang: en
  - tags


# extra:
#   analytics:
#     provider: google
#     property: 'UA-99574439-3'
#   version:
#     provider: mike
#     default: 3.x
#   social:
#     - type: 'github'
#       link: 'https://github.com/jikan-me'
#     - type: 'twitter'
#       link: 'https://twitter.com/irfanDahir'

# copyright: '2022 Jikan'

# # Repository
repo_name: 'jikan-me/jikan'
repo_url: 'https://github.com/jikan-me/jikan'

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - meta
  - codehilite:
      guess_lang: true
      linenums: false
  - footnotes
  - toc:
      permalink: true



## Pages
nav:
  - Home: index.md 
  - Installation: installation.md
  - Getting Started: 'getting-started.md'
  - Usage:
    - Anime: 
      - Anime: 'usage/anime/main.md'
      - Characters & Staff: 'usage/anime/characters-and-staff.md'
      - Episodes: 'usage/anime/episodes.md'
      - Episode: 'usage/anime/episode.md'
      - News: 'usage/anime/news.md'
      - Forum: 'usage/anime/forum.md'
      - Videos: 'usage/anime/videos.md'
      - Video Episodes: 'usage/anime/videos-episodes.md'
      - Pictures: 'usage/anime/pictures.md'
      - Stats: 'usage/anime/stats.md'
      - Reviews: 'usage/anime/reviews.md'
      - Recommendations: 'usage/anime/recommendations.md'
      - Recently Updated By Users: 'usage/anime/recently-updated-by-users.md'
      - More Info: 'usage/anime/more-info.md'
    - Manga:
      - Manga: 'usage/manga/main.md'
      - Characters: 'usage/manga/characters.md'
      - News: 'usage/manga/news.md'
      - Forum: 'usage/manga/forum.md'
      - Pictures: 'usage/manga/pictures.md'
      - Stats: 'usage/manga/stats.md'
      - More Info: 'usage/manga/more-info.md'
    - Character:
      - Character: 'usage/character/main.md'
      - Pictures: 'usage/character/pictures.md'
    - Person:
      - Person: 'usage/person/main.md'
      - Pictures: 'usage/person/pictures.md'
    - Search:
      - Anime: 'usage/search/anime.md'
      - Manga: 'usage/search/manga.md'
      - Character: 'usage/search/character.md'
      - Person: 'usage/search/person.md'
    - Seasonal: 'usage/seasonal.md'
    - Schedule: 'usage/schedule.md'
    - Top:
      - Anime: 'usage/top/anime.md'
      - Manga: 'usage/top/manga.md'
      - Character: 'usage/top/character.md'
      - Person: 'usage/top/person.md'
    - Genre:
      - Anime: 'usage/genre/anime.md'
      - Manga: 'usage/genre/manga.md'
    - User:
      - Profile: 'usage/user/profile.md'
      - Friends: 'usage/user/friends.md'
      - History: 'usage/user/history.md'
    - Producer: 'usage/producers.md'
    - Magazine: 'usage/magazines.md'